title: "Ioannis Tsintzas"
description: "Personal site of Ioannis Tsintzas: CTF writeups, projects and more."

baseurl: ""

permalink: /:title
paginate: 3
paginate_path: /page/:num/

exclude:
- README.md
- Gemfile
- Gemfile.lock

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# This line allows posts to have a future date. 
# I don't need it, but like, LOL.
# future: true

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: tocttou/hacker-blog
  
# Custom variables
owner : "Ioannis Tsintzas"
year : "2026"
